runtime: nodejs12

entrypoint: node server.js

env_variables:
  USE_BASIC_AUTH: "true"

handlers:
- url: /token
  secure: always
  script: auto

- url: /
  static_files: build/index.html
  upload: build/index.html

- url: /(.*)
  static_files: build/\1
  upload: build/(.*)
