runtime: nodejs12

handlers:
- url: /static
  secure: always
  static_dir: build/static

- url: /(.*\.(json|ico|js|txt|png))$
  secure: always
  static_files: build/\1
  upload: build/.*\.(json|ico|js|txt|png)$

- url: .*
  secure: always
  static_files: build/index.html
  upload: build/index.html
