runtime: nodejs12

entrypoint: node server.js

env_variables:
  USE_BASIC_AUTH: "true"

handlers:
- url: /token
  secure: always
  script: auto

- url: /static
  secure: always
  static_dir: build/static

- url: /(.*\.(json|ico|js|txt))$
  secure: always
  static_files: build/\1
  upload: build/.*\.(json|ico|js|txt)$

- url: .*
  secure: always
  static_files: build/index.html
  upload: build/index.html
